name: Build docs
on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      run: |
        curl -sSL \
          "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py" | python
        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-3.10-${{ hashfiles('poetry.lock')}}
    - name: Install dependency
      run: |
        poetry config virtualenvs.in-project true
        poetry run pip install -U pip
        poetry install

    - name: Upload docs
      run: |
        cd docs && mkdocs gh-deploy
